### ISSUE TITLE
Supported model causes error

### ISSUE THREAD

**Issue by ClaudeHu** [qdrant/fastembed#104]
When I tried to embed with one of the [supported models](https://qdrant.github.io/fastembed/examples/Supported_Models/):
```python
from fastembed.embedding import FlagEmbedding as Embedding
embedding_model = Embedding(model_name="jinaai/jina-embeddings-v2-base-en")
```

It gave this error:
```
Was not able to download fast-jina-embeddings-v2-base-en.tar.gz, trying jinaai-jina-embeddings-v2-base-en.tar.gz
Traceback (most recent call last):
  File "/home/claudehu/Desktop/repo/geniml_dev/venv/lib/python3.10/site-packages/fastembed/embedding.py", line 339, in retrieve_model
    self.download_file_from_gcs(
  File "/home/claudehu/Desktop/repo/geniml_dev/venv/lib/python3.10/site-packages/fastembed/embedding.py", line 245, in download_file_from_gcs
    raise PermissionError(
PermissionError: Authentication Error: You do not have permission to access this resource. Please check your credentials.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/snap/pycharm-community/364/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/claudehu/Desktop/repo/geniml_dev/venv/lib/python3.10/site-packages/fastembed/embedding.py", line 422, in __init__
    self._model_dir = self.retrieve_model(model_name, cache_dir)
  File "/home/claudehu/Desktop/repo/geniml_dev/venv/lib/python3.10/site-packages/fastembed/embedding.py", line 346, in retrieve_model
    self.download_file_from_gcs(
  File "/home/claudehu/Desktop/repo/geniml_dev/venv/lib/python3.10/site-packages/fastembed/embedding.py", line 245, in download_file_from_gcs
    raise PermissionError(
PermissionError: Authentication Error: You do not have permission to access this resource. Please check your credentials.
```

**Comment by Anush008** [comment]
Jina models are accessible using the `JinaEmbedding` class.
After the recent update release, all the models are available in the `TextEmbedding` class.
