### ISSUE TITLE
Sample code gave an error

### ISSUE THREAD

**Issue by ClaudeHu** [qdrant/fastembed#114]
I tried to run the example code given in README:

```python
from fastembed import TextEmbedding
from typing import List
import numpy as np

documents: List[str] = [
    "passage: Hello, World!",
    "query: Hello, World!", # these are two different embedding
    "passage: This is an example passage.",
    "fastembed is supported by and maintained by Qdrant." # You can leave out the prefix but it's recommended
]
embedding_model = TextEmbedding(model_name="BAAI/bge-base-en")
embeddings: List[np.ndarray] = list(embedding_model.embed(documents)) # Note the list() call - this is a generator
```
However, this gave such an error:
```
Traceback (most recent call last):
  File "/snap/pycharm-community/364/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
ImportError: cannot import name 'TextEmbedding' from 'fastembed' (unknown location)

```

**Comment by NirantK** [comment]
Hey @ClaudeHu — sorry for the confusion here, these changes have not been pushed to PyPi yet. I'll do that and update you here
