### ISSUE TITLE
failed to retrieve a model from cache

### ISSUE THREAD

**Issue by joein** [qdrant/fastembed#136]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/qdrant_fastembed.py", line 339, in add
    self.upload_points(
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 1872, in upload_points
    return self._client.upload_points(
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/qdrant_remote.py", line 2377, in upload_points
    self._upload_collection(
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/qdrant_remote.py", line 2329, in _upload_collection
    for _ in updater.process(batches_iterator):
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/uploader/rest_uploader.py", line 79, in process
    for batch in items:
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/uploader/uploader.py", line 34, in iterate_records_batches
    for record_batch in record_batches:
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/uploader/uploader.py", line 20, in iter_batch
    b = list(islice(source_iter, size))
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/qdrant_fastembed.py", line 213, in _points_iterator
    for idx, meta, (doc, vector) in zip(ids, metadata, encoded_docs):
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/qdrant_fastembed.py", line 148, in _embed_documents
    embedding_model = self._get_or_init_model(model_name=embedding_model_name)
  File "<path>/venv/lib/python3.9/site-packages/qdrant_client/qdrant_fastembed.py", line 132, in _get_or_init_model
    cls.embedding_models[model_name] = TextEmbedding(
  File "<path>/venv/lib/python3.9/site-packages/fastembed/text/text_embedding.py", line 59, in __init__
    self.model = embedding(model_name, cache_dir, threads, **kwargs)
  File "<path>/venv/lib/python3.9/site-packages/fastembed/text/onnx_embedding.py", line 186, in __init__
    model_path = locate_model_file(self._model_dir, ["model.onnx", "model_optimized.onnx"])
  File "<path>/venv/lib/python3.9/site-packages/fastembed/common/model_management.py", line 28, in locate_model_file
    raise ValueError(f"Could not find either of {', '.join(file_names)} in {model_dir}")
ValueError: Could not find either of model.onnx, model_optimized.onnx in /var/folders/jm/z8r2rd510512zv_4nq51p1mw0000gn/T/fastembed_cache/fast-bge-small-en
```

UPD:

Steps to reproduce:

```python
from fastembed import TextEmbedding

TextEmbedding(model_name='BAAI/bge-base-en', cache_dir='local')
```

- Launch the code
- Interrupt downloading process
- Launch again: crash

**Comment by NirantK** [comment]
Closing this because of inactivity + unable to reproduce with v0.2.4 — please open it again if this is still unsolved @joein ?

**Comment by joein** [comment]
Sorry, I probably got it when I tried to download a model after an interrupted attempt of downloading it

**Comment by joein** [comment]
I reopen it and will take care of it on my own
