### ISSUE TITLE
Issue with 1.5 model

### ISSUE THREAD

**Issue by AmanKishore** [qdrant/fastembed#29]
```
>>> Embedding("BAAI/bge-small-en-v1.5")
Was not able to download fast-bge-small-en-v1.5.tar.gz, trying BAAI-bge-small-en-v1.5.tar.gz
Traceback (most recent call last):
  File "/Users/amankishore/Library/Python/3.9/lib/python/site-packages/fastembed/embedding.py", line 339, in retrieve_model
    self.download_file_from_gcs(
  File "/Users/amankishore/Library/Python/3.9/lib/python/site-packages/fastembed/embedding.py", line 245, in download_file_from_gcs
    raise PermissionError(
PermissionError: Authentication Error: You do not have permission to access this resource. Please check your credentials.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amankishore/Library/Python/3.9/lib/python/site-packages/fastembed/embedding.py", line 422, in __init__
    self._model_dir = self.retrieve_model(model_name, cache_dir)
  File "/Users/amankishore/Library/Python/3.9/lib/python/site-packages/fastembed/embedding.py", line 346, in retrieve_model
    self.download_file_from_gcs(
  File "/Users/amankishore/Library/Python/3.9/lib/python/site-packages/fastembed/embedding.py", line 245, in download_file_from_gcs
    raise PermissionError(
PermissionError: Authentication Error: You do not have permission to access this resource. Please check your credentials.
```

**Comment by NirantK** [comment]
Hey @AmanKishore, I am unable to reproduce this right now. Can you sharing a Colab notebook which reproduces this? Should be 2-5 lines of code which you can copy paste perhaps?

**Comment by AmanKishore** [comment]
Looks like it's working now

**Comment by ernests** [comment]
@NirantK I actually got the same error message

Installed and tried to run it

```python
from fastembed.embedding import FlagEmbedding as Embedding

embedding_model = Embedding(model_name="BAAI/bge-large-en-v1.5", max_length=512)
```

Got this message:
Was not able to download fast-bge-large-en-v1.5.tar.gz, trying BAAI-bge-large-en-v1.5.tar.gz

I think the error is because of permissions on googleapis. It can't access the tar file for bge-large-en

![image](https://github.com/qdrant/fastembed/assets/197629/76c15bfb-ed04-440c-9b18-268e022adc3e)

**Comment by ernests** [comment]
Sorry, checked with "BAAI/bge-base-en-v1.5" and it works. I tried "large" and it is not in supported model list.

By the way, why not support "large" :)

**Comment by NirantK** [comment]
Large isn't fast enough on CPU yet 😥
